### ISSUE TITLE
code availability

### ISSUE THREAD

**Issue by ttsesm** [cfernandezlab/Lines-and-Vanishing-Points-directly-on-Panoramas#1]
Dear Clara, thanks for sharing your work. Actually your work seems quite interesting and I am working on a slightly different project where we use fish-eye cameras. I have two questions though, if I am not wrong this source code is a subpart of the "Layouts from Panoramic Images with Geometry and Deep Learning" work, right? Thus, I was wondering whether it would be easy for you to share the code for the whole pipeline that you are following in the mentioned paper, for example the room layout estimation procedure. The second question is whether your work would work on fish-eye (omnidirectional) images and if you tried it?

**Comment by cfernandezlab** [comment]
Hi Theodore,
Thank you for your interest in our work! And I’m sorry for the late reply.
The code to share is actually paused now since we are focused on the next step, however we plan to upload it in the short-term.
Regarding your second question, we haven't tried it since we use the full context to generate the layouts. 
Maybe you could be interested on this paper of one of our authors which works with fisheye cameras: 'Peripheral Expansion of Depth Information via Layout Estimation with Fisheye Camera' (ECCV 2016).

**Comment by ttsesm** [comment]
Hi Clara,
Thanks for the reply. Do you have any rough estimate about how long this "short-term" period would be, because I would like to try your work in practice for my project and of course cite your work.

Regarding the other paper that you suggested me, I am aware of Alejandro's work. I have also send him an email (about a month ago or something) regarding the same question and whether he could share some source code especially the way he extracts/estimates the room layout (I think this part should be similar in your work as well). However, I haven't got an answer since then. I do not know whether would be possible for you to contact Alejandro and ask him since I see you belong in the same research group.

To be honest with you I find both your work and Alejandro's really interesting. In my project I am trying to estimate the spatial illumination by using only an RGBD input (you can have a look here, https://arxiv.org/pdf/1809.07558.pdf). However, my estimation is limited only to the part of the scene that the FOV of the depth sensor can see. Thus, I wanted to used either yours or Alejandro's work in order to check whether I can retrieve a more complete 3d layout of the scene, by taking advantage of the the fish-eye view as well, which I can use then for my spatial light estimation.

Thank you for your time and I am looking forward to hearing back from you.

Best,
Theo
